### PR TITLE
Upgrade to Micronaut 4

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
This does not seem to work after running `okta start` and `mvn mn:run`. I'll investigate when I get back from summer vacation.

**Comment by mraible** [comment]
@sdelamo I upgraded this example to use Micronaut 4. It seems like everything is configured correctly. However, when I click on Login, it doesn't do anything. Any ideas?

**Comment by sdelamo** [comment]
@mraible the issue is you were missing the snake yaml dependency. I have created a PR with this one as base: 

https://github.com/okta-samples/okta-micronaut-sample/pull/57

**Comment by mraible** [comment]
@sdelamo Thank you so much for your help with this! You're awesome. 🤩

**Pull request merged**
